"""Add execution_type to history

Revision ID: 208c8ea6809a
Revises: a2b3c4d5e6f7
Create Date: 2026-03-13 02:18:28.572821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208c8ea6809a'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_front_recordings_feature_id'), table_name='front_recordings')
    op.drop_index(op.f('ix_front_recordings_id'), table_name='front_recordings')
    op.drop_table('front_recordings')
    op.add_column('api_test_execution_history', sa.Column('execution_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_api_test_execution_history_execution_type'), 'api_test_execution_history', ['execution_type'], unique=False)
    op.add_column('api_test_execution_history_archive', sa.Column('execution_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_api_test_execution_history_archive_execution_type'), 'api_test_execution_history_archive', ['execution_type'], unique=False)
    op.create_foreign_key(None, 'flow_data', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flow_data', type_='foreignkey')
    op.drop_index(op.f('ix_api_test_execution_history_archive_execution_type'), table_name='api_test_execution_history_archive')
    op.drop_column('api_test_execution_history_archive', 'execution_type')
    op.drop_index(op.f('ix_api_test_execution_history_execution_type'), table_name='api_test_execution_history')
    op.drop_column('api_test_execution_history', 'execution_type')
    op.create_table('front_recordings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requests', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interactions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('front_recordings_feature_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('front_recordings_pkey'))
    )
    op.create_index(op.f('ix_front_recordings_id'), 'front_recordings', ['id'], unique=False)
    op.create_index(op.f('ix_front_recordings_feature_id'), 'front_recordings', ['feature_id'], unique=False)
    # ### end Alembic commands ###
