"""increase_id_length

Revision ID: 49d22a6e5bc4
Revises: 8c2d7dae8708
Create Date: 2026-01-21 20:44:27.111876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d22a6e5bc4'
down_revision: Union[str, Sequence[str], None] = '8c2d7dae8708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
