"""Add node_name to history

Revision ID: 88928c360ce7
Revises: 
Create Date: 2026-01-20 10:56:45.695950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88928c360ce7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Add node_name column if it doesn't exist
    columns = [col['name'] for col in inspector.get_columns('api_test_execution_history')]
    if 'node_name' not in columns:
        op.add_column('api_test_execution_history', sa.Column('node_name', sa.String(length=255), nullable=True))




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_test_execution_history', 'node_name')
    op.create_table('step',
    sa.Column('expected_execution_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scenary_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('step_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('step_pkey'))
    )
    op.create_table('sub_feature',
    sa.Column('parent_scenary_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('feature_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sub_feature_pkey'))
    )
    op.create_table('scenary',
    sa.Column('automated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('complexity', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('core', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('positive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('regression', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('row_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scenary_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('parent_feature_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pre-requisito', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scenary_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scenary_pkey'))
    )
    op.create_table('feature',
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('scenary_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('feature_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('feature_pkey'))
    )
    # ### end Alembic commands ###
