"""add_faker_options

Revision ID: 8c2d7dae8708
Revises: 88928c360ce7
Create Date: 2026-01-20 11:58:56.840735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2d7dae8708'
down_revision: Union[str, Sequence[str], None] = '88928c360ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('variables')]
    
    if 'faker_options' not in columns:
        op.add_column('variables', sa.Column('faker_options', sa.JSON(), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variables', 'faker_options')
    # ### end Alembic commands ###
