"""add_performance_schedule_fields

Revision ID: c2caa2fbb80f
Revises: f14c3fdbe634
Create Date: 2026-06-10 20:26:49.732308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2caa2fbb80f'
down_revision: Union[str, Sequence[str], None] = 'f14c3fdbe634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('virtual_users', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('ramp_up_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'ramp_up_seconds')
    op.drop_column('schedules', 'duration_seconds')
    op.drop_column('schedules', 'virtual_users')
    # ### end Alembic commands ###
