"""add_ai_enabled_to_agent_settings

Revision ID: c88d9b665407
Revises: 49d22a6e5bc4
Create Date: 2026-02-04 18:23:10.503452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88d9b665407'
down_revision: Union[str, Sequence[str], None] = '49d22a6e5bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_settings', sa.Column('ai_enabled', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('default_notification_urls', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_schedules_company_id'), 'schedules', ['company_id'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_company_id'), table_name='schedules')
    op.drop_column('companies', 'default_notification_urls')
    op.drop_column('agent_settings', 'ai_enabled')
    # ### end Alembic commands ###
