"""add_ai_enabled_to_agent_settings

Revision ID: c88d9b665407
Revises: 49d22a6e5bc4
Create Date: 2026-02-04 18:23:10.503452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88d9b665407'
down_revision: Union[str, Sequence[str], None] = '49d22a6e5bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Check agent_settings
    agent_cols = [col['name'] for col in inspector.get_columns('agent_settings')]
    if 'ai_enabled' not in agent_cols:
        op.add_column('agent_settings', sa.Column('ai_enabled', sa.Boolean(), nullable=True))
    
    # Check companies
    comp_cols = [col['name'] for col in inspector.get_columns('companies')]
    if 'default_notification_urls' not in comp_cols:
        op.add_column('companies', sa.Column('default_notification_urls', sa.String(length=500), nullable=True))
    
    # Check indexes on schedules
    schedules_indexes = [idx['name'] for idx in inspector.get_indexes('schedules')]
    if 'ix_schedules_company_id' not in schedules_indexes:
        op.create_index(op.f('ix_schedules_company_id'), 'schedules', ['company_id'], unique=False)
    if 'ix_schedules_status' not in schedules_indexes:
        op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_company_id'), table_name='schedules')
    op.drop_column('companies', 'default_notification_urls')
    op.drop_column('agent_settings', 'ai_enabled')
    # ### end Alembic commands ###
