"""add_p50_latency

Revision ID: cd5f1ab8bd2d
Revises: ea403957c473
Create Date: 2026-06-05 14:16:19.375378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5f1ab8bd2d'
down_revision: Union[str, Sequence[str], None] = 'ea403957c473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_test_results', sa.Column('p50_latency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_test_results', 'p50_latency')
    # ### end Alembic commands ###
