"""add_visible_execution_to_schedule

Revision ID: d542d87213ca
Revises: 865d2a51d5e6
Create Date: 2026-05-28 09:52:35.391933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd542d87213ca'
down_revision: Union[str, Sequence[str], None] = '865d2a51d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_front_recordings_feature_id'), table_name='front_recordings')
    op.drop_index(op.f('ix_front_recordings_id'), table_name='front_recordings')
    op.drop_table('front_recordings')
    op.drop_index(op.f('idx_history_batch_time'), table_name='api_test_execution_history')
    op.create_index('idx_history_batch_time', 'api_test_execution_history', ['batch_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_history_project_time'), table_name='api_test_execution_history')
    op.create_index('idx_history_project_time', 'api_test_execution_history', ['project_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_history_schedule_time'), table_name='api_test_execution_history')
    op.create_index('idx_history_schedule_time', 'api_test_execution_history', ['schedule_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_product_mobile_settings_id'), 'product_mobile_settings', ['id'], unique=False)
    op.drop_constraint(op.f('product_mobile_settings_product_id_fkey'), 'product_mobile_settings', type_='foreignkey')
    op.create_foreign_key(None, 'product_mobile_settings', 'products', ['product_id'], ['id'])
    op.alter_column('products', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'web'::character varying"))
    op.add_column('schedules', sa.Column('visible_execution', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'visible_execution')
    op.alter_column('products', 'platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'web'::character varying"))
    op.drop_constraint(None, 'product_mobile_settings', type_='foreignkey')
    op.create_foreign_key(op.f('product_mobile_settings_product_id_fkey'), 'product_mobile_settings', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_mobile_settings_id'), table_name='product_mobile_settings')
    op.drop_index('idx_history_schedule_time', table_name='api_test_execution_history')
    op.create_index(op.f('idx_history_schedule_time'), 'api_test_execution_history', ['schedule_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_history_project_time', table_name='api_test_execution_history')
    op.create_index(op.f('idx_history_project_time'), 'api_test_execution_history', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_history_batch_time', table_name='api_test_execution_history')
    op.create_index(op.f('idx_history_batch_time'), 'api_test_execution_history', ['batch_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('front_recordings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requests', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interactions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('front_recordings_feature_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('front_recordings_pkey'))
    )
    op.create_index(op.f('ix_front_recordings_id'), 'front_recordings', ['id'], unique=False)
    op.create_index(op.f('ix_front_recordings_feature_id'), 'front_recordings', ['feature_id'], unique=False)
    # ### end Alembic commands ###
