"""remove deprecated flow json columns

Revision ID: ea403957c473
Revises: d542d87213ca
Create Date: 2026-06-03 18:39:21.184432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea403957c473'
down_revision: Union[str, Sequence[str], None] = 'd542d87213ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_data', 'edges')
    op.drop_column('flow_data', 'card_data')
    op.drop_column('flow_data', 'nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_data', sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('flow_data', sa.Column('card_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('flow_data', sa.Column('edges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
