"""Add healed_selector

Revision ID: f14c3fdbe634
Revises: cd5f1ab8bd2d
Create Date: 2026-06-08 00:51:28.893916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14c3fdbe634'
down_revision: Union[str, Sequence[str], None] = 'cd5f1ab8bd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_test_execution_history', sa.Column('healed_selector', sa.String(length=500), nullable=True))
    op.add_column('api_test_execution_history_archive', sa.Column('healed_selector', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_test_execution_history_archive', 'healed_selector')
    op.drop_column('api_test_execution_history', 'healed_selector')
    # ### end Alembic commands ###
